# yaml-language-server: $schema=https://json.schemastore.org/swagger-2.0.json
swagger: "2.0"
info:
  description: "This TLI group 4's backend API which makes"
  version: "1.0.0"
  title: "TLI Group 4 - GRIMM"
  license:
    name: "MIT"
    url: "https://mit-license.org"
basePath: "/v1"
tags:
- name: "loans"
  description: "Everything related to loan information"
- name: "addOns"
  description: "Things related to car add-ons"
- name: "vehicles"
  description: "All things related to vehicles"
schemes:
- "https"
paths:
  /vehicle:
    post:
      tags:
      - "vehicles"
      summary: "Get vehicles matching data"
      consumes:
      - "text/plain"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Vehicle string to search for"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "All matching cars"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Car"
  /addOns:
    post:
      tags:
      - "addOns"
      summary: "Get the vehicle containing all available add-ons for a vehicle"
      consumes:
      - "text/plain"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "The vehicle id to fetch addons for"
        required: true
        schema:
          type: "number"
      responses:
        "200":
          description: "The all available add-ons for a vehicle"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AddOn"
  /loan:
    post:
      tags:
      - "loans"
      summary: "Get the information of the loan available to a buyer considering a purchase"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "The car (containing add-ons) and car buyer to fetch data for. loopMax is the maximum number of times to loop calls to Senso /rate to calculate add-on budget (-1 means loop until error)"
        required: true
        schema:
          type: "object"
          required:
          - "car"
          - "carBuyer"
          - "loopMax"
          properties:
            car:
              $ref: "#/definitions/Car"
            carBuyer:
              $ref: "#/definitions/CarBuyer"
            loopMax:
              type: "number"
      responses:
        "200":
          description: "The data on the loan"
          schema:
            $ref: "#/definitions/LoanData"
definitions:
  AddOn:
    type: "object"
    properties:
      name:
        type: "string"
      price:
        type: "number"
      description:
        type: "string"
  Car:
    type: "object"
    required:
    - "id"
    - "make"
    - "model"
    - "year"
    - "addOns"
    properties:
      id:
        type: "number"
      make:
        type: "string"
      model:
        type: "string"
      year:
        type: "number"
      price:
        type: "number"
      addOns:
        type: "array"
        items:
          $ref: "#/definitions/AddOn"
  CarBuyer:
    type: "object"
    required:
    - "budget"
    - "creditScore"
    properties:
      budget:
        type: "number"
      creditScore:
        type: "number"
  LoanData:
    type: "object"
    required:
    - 'interestRate'
    - "installment"
    - "sensoScore"
    - "amount"
    - "term"
    - "interestSum"
    - "installments"
    - "addOnBudget"
    properties:
      interestRate:
        type: "number"
      installment:
        type: "number"
      sensoScore:
        type: "string"
      amount:
        type: "number"
      term:
        type: "number"
      interestSum:
        type: "number"
      installments:
        type: "array"
        items:
          type: "object"
          properties:
            capital:
              type: "number"
            interest:
              type: "number"
            remain:
              type: "number"
            installment:
              type: "number"
            interestSum:
              type: "number"
      addOnBudget:
        type: "number"
